version: '3.1'

services:
  ledger-scraper:
    build: ./ledger_scraper
    depends_on:
      - kafka

  stream-processor:
    build: ./stream_processor
    depends_on:
      - ledger-scraper

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
    ports:
      - "9092:9092"